<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<%--
Name: Mark Wlodawski
 Course: CNT 4714 – Spring 2026 – Project Four
 Assignment title: A Three-Tier Distributed Web-Based Application
 Date: April 27, 2026
--%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CNT 4714 - Enterprise System - Root User</title>
    <style>
        body { font-family: sans-serif; background-color: #f0f0f0; padding: 20px; }
        .header { color: blue; text-align: center; }
        .form-container { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        textarea { width: 100%; font-family: monospace; border: 1px solid #ccc; }
        table { border-collapse: collapse; width: 100%; background: white; margin-top: 20px; }
        th, td { border: 1px solid black; padding: 8px; text-align: left; }
        th { background-color: #4CAF50; color: white; }
        .message { color: green; font-weight: bold; margin-top: 10px; }
        .error { color: red; font-weight: bold; margin-top: 10px; }
    </style>
</head>
<body>

    <h1 class="header">Welcome to the Spring 2026 Project 4 Enterprise System</h1>
    <h2 class="header">Root User Client Page</h2>

    <div class="form-container">
        <p>Enter your SQL statement in the box below and click the button to execute.</p>
        
        <form action="${pageContext.request.contextPath}/RootUserServlet" method="POST">
            <textarea name="sqlCommand" rows="10" placeholder="Enter SQL here...">${sqlCommand}</textarea>
            <br><br>
            <input type="submit" value="Execute Command">
            <input type="reset" value="Reset Form">
        </form>

        <%-- This section displays the messages from the Servlet --%>
        <div class="message">
            <% if (request.getAttribute("message") != null) { %>
                <%= request.getAttribute("message") %>
            <% } %>
        </div>

        <div class="error">
            <% if (request.getAttribute("error") != null) { %>
                <%= request.getAttribute("error") %>
            <% } %>
        </div>
    </div>

    <%-- This section displays the HTML Table generated by the Servlet --%>
    <div id="resultTable">
        <% if (request.getAttribute("table") != null) { %>
            <%= request.getAttribute("table") %>
        <% } %>
    </div>

</body>
</html>